### ISSUE TITLE
what advantage does this package have over using zod directly?

### ISSUE THREAD

**Issue by NyllRE** [wobsoriano/h3-zod#12]
sorry for this is not an issue but a question, but I am new to zod and I've been trying to use formkit with the zod plugin in nuxt and wanted to use zod in the backend for validation. but I felt like using zod directly does the job.

so I was wondering what advantages does this package offer to my codebase and is it worth adding another dependency to my project?

**Comment by wobsoriano** [comment]
You're not gonna need anymore starting with H3 1.8.0 :) - https://unjs.io/blog/2023-08-15-h3-towards-the-edge-of-the-web#runtime-type-safe-request-utils

To answer your question, they're meant to simplify your code by encapsulating common Zod tasks and reducing duplication.
