### ISSUE TITLE
Missing type SafeParseError when there is error

### ISSUE THREAD

**Issue by calebeaires** [wobsoriano/h3-zod#7]
zod: 3.21.4
h3-zod: 0.4.0

Property 'error' does not exist on type 'SafeParseReturnType<ZodObject<{ email: ZodString; password: ZodString; firstName: ZodOptional<ZodString>; lastName: ZodOptional<ZodString>; name: ZodOptional<...>; tags: ZodArray<...>; }, UnknownKeysParam, ZodTypeAny, { ...; }, { ...; }>, { ...; }>'.   Property 'error' does not exist on type 'SafeParseSuccess<{ email?: string; password?: string; firstName?: string; lastName?: string; name?: string; tags?: string[]; }>'.

When doing a wrong body request, the router below return an status and error property, but typescript give us an error

```ts

export default defineEventHandler(async (event) => {
    const body = await zh.useSafeValidatedBody(event, {
        email: z.string().email(),
        password: z.string().min(8),
        firstName: z.string().optional(),
        lastName: z.string().optional(),
        name: z.string().optional(),
        tags: z.array(z.string()).min(1)
    });

    // typescript warning here
    console.log('body', body.error);

    return body;

});
```

**Comment by wobsoriano** [comment]
You should typeguard first using the `success` property:

```ts
const body = await useSafeValidatedBody(event, schema)

if (!body.success) {
  body.error.errors // recognized
}
```

**Comment by fikrihanda** [comment]
im still get error type with property error

![image](https://github.com/wobsoriano/h3-zod/assets/37224559/f9d1f73b-e537-47da-b954-a218db4d502d)

but with success true i can get data 

![image](https://github.com/wobsoriano/h3-zod/assets/37224559/aa64be98-4f20-41ee-9a6a-54c07726ffda)
