### ISSUE TITLE
Validate cookie

### ISSUE THREAD

**Issue by xibman** [wobsoriano/h3-zod#9]
Hi Thanks for you great job

It can be interesting to have a dedicated method to parse cookie content.

With the usage of getCookie() method  if data is stored as json 

`zodSchema.parse(JSON.stringify(getCookie(event, 'cookie_name')))`

**Comment by wobsoriano** [comment]
Hi, I have no plan on supporting cookie validation. Also, H3 1.8.0 has [Runtime + Type-Safe Request Utils](https://unjs.io/blog/2023-08-15-h3-towards-the-edge-of-the-web#runtime-type-safe-request-utils) built-in and you might not need this package anymore.
